name: UbuntuBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@v2
      - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Assembly Build
        working-directory: ${{env.GITHUB_WORKSPACE}}/Project1
        run: gcc Source.cpp

      - name: Upload to GitHub Actions Artifact Storage
        uses: actions/upload-artifact@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 
          name: hello.exe
          path: Project1/hello.exe

      - name: Upload to Azure Blob Storage
        id: upload
        uses: github-developer/upload-azure-blob@v1
        with:
          account: devopstest
          destination: devopstestcontainer
          source: Project1/hello.exe