name: UbuntuBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install GCC
      run: |
        sudo apt install gcc-10 g++-10

    - name: Assembly Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        gcc Project1/Source.cpp
        ls -la
        
    - name: Get short SHA
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: bash
      #run: git_hash=$(git rev-parse --short "$GITHUB_SHA")
      run: echo "git_hash=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_HASH

    - name: Upload to GitHub Actions Artifact Storage
      uses: actions/upload-artifact@v1
      with:
        name: artifact-name-${{ github.run_number }}-${{ github.sha }}-${ GITHUB_BRANCH }
        path: a.out

    #- name: Upload to blob storage
    #  uses: azure/CLI@v1
    #  with:
    #    inlineScript: |
    #        az storage blob upload-batch --account-name devopstest --auth-mode key -d '$web' -s a.out

    #- name: Upload to Azure Blob Storage
    #  id: upload
    #  uses: github-developer/upload-azure-blob@v1
    #  with:
    #    account: devopstest
    #    destination: devopstestcontainer
    #    source: Project1/hello.exe
