name: SconsGCCBuild

on: [push]

env:
  BUILD_TYPE: Debug

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install scons
          
      - name: Build
        working-directory: ${{runner.workspace}}/Project1/
        run: scons
